server:
  port: 8088

spring:
  datasource:                                          #数据源相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    password: 123456
  redis:
    database: 1
    host: 192.168.187.129
    port: 6379
    password: imooc

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #sql打印
