server:
  port: 7077

spring:
  datasource:                                          #数据源相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    password: 123456